### ISSUE TITLE
Resizing issue - constraints vs. frame?

### ISSUE THREAD

**Issue by smhk** [GlobakMaxim/PlaceholderTextView#1]
Hi Maxim, this is very high quality, very professional, we are going to use it in a project.

One thing -

* you are making a frame for the subview.  it is old-fashioned, it can break, have you considered using **constraints**?  What about something like the code below to make the constraints on the fly? (Actually, it would be a little different, you probably want the placeholder text at the "top" not "center" if the text view is tall ...)

* it is extremely common that UITextView change height, it is normal these days to have UITextView change height on the fly as the user types, etc.  you have it in a stack view, everything resizes. In fact, does PlaceholderTextView **allow for resizing**?

cheers!
    
```
    func bindEdgesToSuperview() { // keywords, expand, attach, fit
    	
        guard let s = superview else {
            preconditionFailure("`superview` nil in bindEdgesToSuperview")
        }
		
		translatesAutoresizingMaskIntoConstraints = false
		leadingAnchor.constraint(equalTo: s.leadingAnchor).isActive = true
		trailingAnchor.constraint(equalTo: s.trailingAnchor).isActive = true
		topAnchor.constraint(equalTo: s.topAnchor).isActive = true
		bottomAnchor.constraint(equalTo: s.bottomAnchor).isActive = true
	}

```

**Comment by GlobakMaxim** [comment]
Hello!
Thank you for your issue.
Tomorrow at morning I will check the resilience of resizing the PlaceholderTextView. But before I had no problems using CGRect instead of Constraints

**Comment by GlobakMaxim** [comment]
1) I have several reasons to use Frame instead of Constraints. One of them: for many measurements Frame works faster and it seems to me in such a simple situation it is not necessary to overload the subview with constraints. 
One more, that placeholder should look like a ghost from the text in my opinion =)
(It's about -> (Actually, it would be a little different, you probably want the placeholder text at the "top" not "center" if the text view is tall ...))
In either case, you can place PlaceholderTextView in any way (Storyboard, Constructions, Frame)

Thank you for suggesting the use of contraints and a warning about breakdowns. I will definitely review this way again.

2 ) Actually PlaceholderTextView are ready for resizing and everything works well. 

p.s. I also created a demo project where everyone can taste it. 
I fixed some bugs with storyboards.
